version: '3.8'
services:
  api:
    container_name: sys-info
    build:
      context: ./
      dockerfile: Dockerfile-dev
    environment:
      - FLASK_APP=api
      - FLASK_DEBUG=1
    ports:
      - "8080:8080"
    volumes:
      - ".:/code"
